import requests
import re

# Configuration
OLLAMA_URL = "http://localhost:11434"
MODEL_NAME = "llama3.2"
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL_NAME = "llama-3.3-70b-versatile"


def check_ollama_status():
    """Check whether Ollama is running and the required model exists.

    Returns:
        tuple: (is_running: bool, has_model: bool, models: list)
    """
    try:
        response = requests.get(f"{OLLAMA_URL}/api/tags", timeout=3)
        if response.status_code != 200:
            return False, False, []
        models_data = response.json().get("models", [])
        models = [model.get("name", "") for model in models_data]
        has_model = any(MODEL_NAME.lower() in model.lower() for model in models)
        return True, has_model, models
    except Exception:
        return False, False, []


def clean_sql(response_text: str) -> str:
    """Extract raw SQL from a model response, stripping markdown and comments.
    """
    if not response_text:
        return ""
    # Grab code block if present
    code_match = re.search(r"```(?:sql)?(.*?)```", response_text, re.DOTALL | re.IGNORECASE)
    sql = code_match.group(1) if code_match else response_text
    # Remove any stray markdown fences
    sql = sql.replace("```sql", "").replace("```", "")
    # Strip leading/trailing whitespace and collapse lines
    lines = []
    for line in sql.splitlines():
        line = line.strip()
        if not line or line.startswith("--"):
            continue
        lines.append(line)
    cleaned = " ".join(lines)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


def quote_columns_with_spaces(sql: str, schema: str) -> str:
    """Quote column names that contain spaces.

    The schema string format produced by schema_tool is assumed to contain
    lines like:
      - my col (TEXT)

    If a column name contains a space, we quote it as "my col".
    """

    columns: list[str] = []

    for line in schema.splitlines():
        line = line.strip()
        if line.startswith("-"):
            # e.g. "- my col (TEXT)" -> "my col"
            col = line[1:].split("(")[0].strip()
            if " " in col:
                columns.append(col)

    for col in columns:
        # Replace bare column tokens with quoted version.
        # This is a best-effort approach; SQL is generated by the model.
        sql = sql.replace(col, f'"{col}"')

    return sql


def generate_sql(question: str, schema: str, provider: str = "ollama", api_key: str | None = None) -> str:

    """Generate SQL from a natural‑language question.

    Args:
        question: User's question.
        schema: Database schema description.
        provider: "ollama" or "groq".
        api_key: Required when provider is "groq".
    """
    prompt = f"""
You are a strict SQLite SQL generator for a READ-ONLY analytics system.

**CRITICAL CONSTRAINTS:**

This system is READ-ONLY. You MUST generate ONLY SELECT queries or CTE (WITH) queries that ultimately SELECT.

FORBIDDEN operations:
- INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, REPLACE, MERGE, EXEC, EXECUTE
- Transaction statements (BEGIN, COMMIT, ROLLBACK)
- PRAGMA modifications, VACUUM, ATTACH, DETACH
- Any data modification operations

If the user's question implies data modification (e.g., "delete", "remove", "update", "drop", "truncate", "create", "insert", "alter"), 
you MUST refuse and explain that only read-only analytical queries are supported.

DATABASE SCHEMA:
{schema}

QUESTION:
{question}

RULES:

1. Use ONLY tables listed in DATABASE SCHEMA.
2. Use ONLY columns listed in DATABASE SCHEMA.
3. NEVER invent tables.
4. NEVER invent columns.
5. Use ONLY the tables and columns that appear in the schema.

6. If only one table exists,
   DO NOT generate JOIN statements.

7. Generate ONLY SELECT or WITH...SELECT queries.

8. Do NOT generate any data modification statements.

9. Return ONLY SQL.

SQL:
"""

    if provider == "groq":
        if not api_key:
            raise ValueError("Groq API key is required for Groq provider")
        headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        payload = {
            "model": GROQ_MODEL_NAME,
            "messages": [
                {
                    "role": "system", 
                    "content": (
                        "You are a strict SQL analyst for a READ-ONLY analytics system. "
                        "Generate only SELECT queries or CTE (WITH) queries that ultimately SELECT. "
                        "Never generate INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, TRUNCATE, or any data modification operations. "
                        "If the user requests data modification, refuse and explain that only read-only analytical queries are allowed."
                    )
                },
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.1,
            "top_p": 0.9
        }
        response = requests.post(GROQ_URL, headers=headers, json=payload, timeout=30)
        if response.status_code != 200:
            raise Exception(f"Groq API Error: {response.text}")
        raw = response.json()["choices"][0]["message"]["content"]
        sql = clean_sql(raw)
        sql = quote_columns_with_spaces(sql, schema)
        return sql
    else:  # Ollama
        payload = {
            "model": MODEL_NAME,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.1, "top_p": 0.9}
        }
        response = requests.post(f"{OLLAMA_URL}/api/generate", json=payload, timeout=60)
        if response.status_code != 200:
            raise Exception(f"Ollama returned {response.status_code}")
        raw = response.json().get("response", "")
        sql = clean_sql(raw)
        sql = quote_columns_with_spaces(sql, schema)
        return sql


if __name__ == "__main__":
    sample_schema = """
Table: uploaded_data
Columns:
- id (INTEGER)
- category (TEXT)
- amount (REAL)
- region (TEXT)
"""
    sample_question = "Show the total amount by category"
    print("Checking Ollama status...")
    status = check_ollama_status()
    print(status)
    if status[0] and status[1]:
        sql = generate_sql(sample_question, sample_schema)
        print("\nGenerated SQL:\n", sql)
    else:
        print("Ollama not ready – cannot generate SQL.")
